# fly.toml app configuration file generated for khulafa-bistro-order on 2025-11-23T12:28:01Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'khulafa-bistro-order'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
